HPO_NAME_REPORT_KEY = 'hpo_name'
FOLDER_REPORT_KEY = 'folder'
TIMESTAMP_REPORT_KEY = 'timestamp'
RESULTS_REPORT_KEY = 'results'
ERRORS_REPORT_KEY = 'errors'
WARNINGS_REPORT_KEY = 'warnings'
NONUNIQUE_KEY_METRICS_REPORT_KEY = 'nonunique_key_metrics'
IS_COMPLETE_REPORT_KEY = 'is_complete'
HEEL_ERRORS_REPORT_KEY = 'heel_errors'
DRUG_CLASS_METRICS_REPORT_KEY = 'drug_class_metrics'
SUBMISSION_ERROR_REPORT_KEY = 'submission_error'
ERROR_OCCURRED_REPORT_KEY = 'error_occurred'
COMPLETENESS_REPORT_KEY = 'completeness'
REPORT_KEYS = [
    HPO_NAME_REPORT_KEY, FOLDER_REPORT_KEY, TIMESTAMP_REPORT_KEY,
    RESULTS_REPORT_KEY, ERRORS_REPORT_KEY, WARNINGS_REPORT_KEY,
    NONUNIQUE_KEY_METRICS_REPORT_KEY, HEEL_ERRORS_REPORT_KEY,
    DRUG_CLASS_METRICS_REPORT_KEY
]
