#!/bin/bash
# Client-side git prepare-commit-msg hook to ensure that the commit message starts
# with an associated Jira tag as specified in curation/tools/validate_commit_message.sh
# Please copy this file to curation/.git/hooks/
# Allow it to be executable using "chmod +x curation/.git/hooks/prepare-commit-msg"

TICKET_REGEX="\[(DC|EDQ) - [[:digit:]]+\][[:space:]]"
ERROR_MSG="The commit message below does not start with the Jira ticket tag, please rename."

set -x

COMMIT_MSG_FILE=$1
msg=$(cat "${COMMIT_MSG_FILE}")

if [[ ! $msg =~ $TICKET_REGEX ]];
then
  echo "${ERROR_MSG}"
  echo "${msg}"
  exit 1
fi
