version: "3"

services:
  # base image upon which all other containers are derived
  develop:
    image: "curation:develop-22.04"
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
      # build-time arguments that can be used within the Dockerfile as though
      # they were envvars.  it may be necessary to replicate some of these in the
      # runtime "environments" config key
      args:
          GSDK_VERSION: 454.0.0
          GSDK_CHECKSUM: 58fd3e6d34e6a6e4a4afbfd3a1470ea23ef7ed6e69841c4eb89829ef833dac2c
          CIRCLECI_CLI_VERSION: "0.1.15973"
          CIRCLECI_CLI_CHECKSUM: "4187a5245f06dd8e1d51d5a99ad40ed9e8963397cecf006fd2d6a04ac374bef6"
          GID: 20
          UID: 502    # run-time environment variable values.
    # may containe duplicates from "build.args" map
    environment:
      APPLICATION_ID: "aou-res-curation-test"
      GOOGLE_CLOUD_PROJECT: "aou-res-curation-test"
      CIRCLE_PROJECT_USERNAME: "all-of-us"
    stdin_open: true # docker run -i
    tty: true        # docker run -t