version: "3"

services:
  # base image upon which all other containers are derived
  develop:
    image: "curation:develop-18.04"
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
      # build-time arguments that can be used within the Dockerfile as though
      # they were envvars.  it may be necessary to replicate some of these in the
      # runtime "environments" config key
      args:
          GSDK_VERSION: "442.0.0"
          GSDK_CHECKSUM: "50a0fdffa532be93eb7f0b618a0586c6e5560fd4d57bc2e290b9f549a2b9f0dc"
          CIRCLECI_CLI_VERSION: "0.1.28528"
          CIRCLECI_CLI_CHECKSUM: "c89c39a3b09396ef6b06d652445b539503c673771745371554cd81bb2095dde5"
    # run-time environment variable values.
    # may containe duplicates from "build.args" map
    environment:
      APPLICATION_ID: "aou-res-curation-test"
      GOOGLE_CLOUD_PROJECT: "aou-res-curation-test"
      CIRCLE_PROJECT_USERNAME: "all-of-us"
    stdin_open: true # docker run -i
    tty: true        # docker run -t