version: "3"

services:
  # base image upon which all other containers are derived
  develop:
    image: "curation:develop-20.04"
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
      # build-time arguments that can be used within the Dockerfile as though
      # they were envvars.  it may be necessary to replicate some of these in the
      # runtime "environments" config key
      args:
          GSDK_VERSION: "438.0.0"
          GSDK_CHECKSUM: "d60554e656a22ec25fc36efaa7843a1f9c9bd1f904b899c019d383686fe4b850"
          CIRCLECI_CLI_VERSION: "0.1.15973"
          CIRCLECI_CLI_CHECKSUM: "4187a5245f06dd8e1d51d5a99ad40ed9e8963397cecf006fd2d6a04ac374bef6"
    # run-time environment variable values.
    # may containe duplicates from "build.args" map
    environment:
      APPLICATION_ID: "aou-res-curation-test"
      GOOGLE_CLOUD_PROJECT: "aou-res-curation-test"
      CIRCLE_PROJECT_USERNAME: "all-of-us"
    stdin_open: true # docker run -i
    tty: true        # docker run -t