version: "3"

services:
  # base image upon which all other containers are derived
  develop:
    image: "curation:develop-22.04"
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
      # build-time arguments that can be used within the Dockerfile as though
      # they were envvars.  it may be necessary to replicate some of these in the
      # runtime "environments" config key
      args:
          GSDK_VERSION: "441.0.0"
          GSDK_CHECKSUM: "b67b0383d71a036846f4cade5467186aacdd3def8f246d03036be6d9419c3b29"
          CIRCLECI_CLI_VERSION: "0.1.28434"
          CIRCLECI_CLI_CHECKSUM: "508675cc7e1be883134a0243e0665b8e40894974ecdf9e3a551d929e516b2e68"
    # run-time environment variable values.
    # may containe duplicates from "build.args" map
    environment:
      APPLICATION_ID: "aou-res-curation-test"
      GOOGLE_CLOUD_PROJECT: "aou-res-curation-test"
      CIRCLE_PROJECT_USERNAME: "all-of-us"
    stdin_open: true # docker run -i
    tty: true        # docker run -t