import cdm

SOURCE_VALUE_EHR_CONSENT = 'EHRConsentPII_ConsentPermission'
CONCEPT_ID_CONSENT_PERMISSION_YES = 1586100  # ConsentPermission_Yes
EHR_CONSENT_TABLE_ID = '_ehr_consent'
PERSON_TABLE = 'person'
PERSON_ID = 'person_id'
OBSERVATION_TABLE = 'observation'
FOREIGN_KEYS_FIELDS = [
    'visit_occurrence_id', 'location_id', 'care_site_id', 'provider_id'
]
RDR_TABLES_TO_COPY = ['person']
EHR_TABLES_TO_COPY = ['death']
DOMAIN_TABLES = list(
    set(cdm.tables_to_map()) - set(RDR_TABLES_TO_COPY + EHR_TABLES_TO_COPY))
TABLES_TO_PROCESS = RDR_TABLES_TO_COPY + EHR_TABLES_TO_COPY + DOMAIN_TABLES
LEFT_JOIN = (
    ' LEFT JOIN'
    ' ('
    ' SELECT *'
    ' FROM ('
    ' SELECT'
    ' *,'
    ' row_number() OVER (PARTITION BY {prefix}.{field}, {prefix}.src_hpo_id ) '
    ' AS row_num'
    ' FROM {dataset_id}.{table} {prefix}'
    ' )'
    ' WHERE row_num = 1'
    ' ) {prefix}  ON t.{field} = {prefix}.src_{field}'
    ' AND m.src_dataset_id = {prefix}.src_dataset_id')

LEFT_JOIN_PERSON = (
    ' LEFT JOIN'
    ' ('
    ' SELECT *'
    ' FROM ('
    ' SELECT'
    ' *,'
    ' row_number() OVER (PARTITION BY {prefix}.{field}, {prefix}.src_hpo_id ) '
    ' AS row_num'
    ' FROM {dataset_id}.{table} {prefix}'
    ' )'
    ' WHERE row_num = 1'
    ' ) {prefix}  ON t.{field} = {prefix}.src_{field}')

EHR_CONSENT_QUERY = (
    ' WITH ordered_response AS\n'
    ' (SELECT'
    ' person_id,'
    ' value_source_concept_id,'
    ' observation_datetime,'
    ' ROW_NUMBER() OVER(PARTITION BY person_id ORDER BY observation_datetime DESC, '
    ' value_source_concept_id ASC) AS rn'
    ' FROM {dataset_id}.observation'
    ' WHERE observation_source_value = \'{source_value_ehr_consent}\')'
    ' SELECT person_id'
    ' FROM ordered_response'
    ' WHERE rn = 1'
    ' AND value_source_concept_id = {concept_id_consent_permission_yes}')

COPY_RDR_QUERY = 'SELECT * FROM {rdr_dataset_id}.{table}'

COPY_EHR_QUERY = (
    '      SELECT * FROM {ehr_dataset_id}.{table} t'
    '      WHERE EXISTS'
    '           (SELECT 1 FROM {combined_dataset_id}.{ehr_consent_table_id} c'
    '            WHERE t.person_id = c.person_id)')

MAPPING_QUERY_WITH_PERSON_CHECK = (
    'SELECT DISTINCT'
    ' \'{rdr_dataset_id}\'  AS src_dataset_id,'
    '  {domain_table}_id  AS src_{domain_table}_id,'
    '  \'rdr\' as src_hpo_id,'
    '  {domain_table}_id + {mapping_constant}  AS {domain_table}_id'
    '  FROM {rdr_dataset_id}.{domain_table}'
    ''
    '  UNION ALL'
    ''
    '  SELECT DISTINCT'
    '  \'{ehr_dataset_id}\'  AS src_dataset_id,'
    '  t.{domain_table}_id AS src_{domain_table}_id,'
    '  v.src_hpo_id AS src_hpo_id,'
    '  t.{domain_table}_id  AS {domain_table}_id'
    '  FROM {ehr_dataset_id}.{domain_table} t'
    '  JOIN {ehr_dataset_id}._mapping_{domain_table}  v on t.{domain_table}_id = v.{'
    'domain_table}_id'
    '  WHERE EXISTS'
    '  (SELECT 1 FROM {combined_dataset_id}.{ehr_consent_table_id} c'
    '  WHERE t.person_id = c.person_id)')

MAPPING_QUERY_WITHOUT_PERSON_CHECK = (
    'SELECT DISTINCT'
    ' \'{rdr_dataset_id}\'  AS src_dataset_id,'
    '  {domain_table}_id  AS src_{domain_table}_id,'
    '  \'rdr\' as src_hpo_id,'
    '  {domain_table}_id + {mapping_constant}  AS {domain_table}_id'
    '  FROM {rdr_dataset_id}.{domain_table}'
    ''
    '  UNION ALL'
    ''
    '  SELECT DISTINCT'
    '  \'{ehr_dataset_id}\'  AS src_dataset_id,'
    '  t.{domain_table}_id AS src_{domain_table}_id,'
    '  v.src_hpo_id AS src_hpo_id,'
    '  t.{domain_table}_id  AS {domain_table}_id'
    '  FROM {ehr_dataset_id}.{domain_table} t'
    '  JOIN {ehr_dataset_id}._mapping_{domain_table}  v on t.{domain_table}_id = '
    'v.{domain_table}_id')

LOAD_QUERY = (
    '    SELECT {cols}'
    '    FROM {rdr_dataset_id}.{domain_table} t'
    '    JOIN'
    '    ('
    '        SELECT *'
    '        FROM ('
    '          SELECT'
    '              *,'
    '              row_number() OVER (PARTITION BY m.src_{domain_table}_id, m.src_hpo_id ) AS row_num'
    '          FROM {combined_dataset_id}.{mapping_table} as m'
    '        )'
    '        WHERE row_num = 1'
    '    ) m        ON t.{domain_table}_id = m.src_{domain_table}_id'
    '       {join_expr}'
    '    WHERE m.src_dataset_id = \'{rdr_dataset_id}\''
    ' '
    '    UNION ALL'
    ''
    '    SELECT {cols}'
    '    FROM'
    '    ('
    '        SELECT *'
    '        FROM ('
    '          SELECT'
    '              *,'
    '              row_number() OVER (PARTITION BY m.{domain_table}_id) AS row_num'
    '          FROM {ehr_dataset_id}.{domain_table} as m'
    '        )'
    '        WHERE row_num = 1'
    '    ) t'
    '    JOIN'
    '    ('
    '        SELECT *'
    '        FROM ('
    '          SELECT'
    '              *,'
    '              row_number() OVER (PARTITION BY m.src_{domain_table}_id, m.src_hpo_id) AS row_num'
    '          FROM {combined_dataset_id}.{mapping_table} as m'
    '        )'
    '        WHERE row_num = 1'
    '    ) m'
    '        ON t.{domain_table}_id = m.src_{domain_table}_id '
    '       {join_expr}'
    '    WHERE m.src_dataset_id = \'{ehr_dataset_id}\''
    '    ')

MAPPED_PERSON_QUERY = ('select {cols} '
                       'from {dataset}.{table} as t '
                       '{join_expr}')

FACT_RELATIONSHIP_QUERY = (
    '\n'
    '  SELECT'
    '    fr.domain_concept_id_1 AS domain_concept_id_1,'
    '    CASE'
    '        WHEN domain_concept_id_1 = {measurement_domain_concept_id}'
    '          THEN m1.measurement_id'
    '        WHEN domain_concept_id_1 = {observation_domain_concept_id}'
    '          THEN o1.observation_id'
    '    END AS fact_id_1,'
    '    fr.domain_concept_id_2,'
    '    CASE'
    '        WHEN domain_concept_id_2 = {measurement_domain_concept_id}'
    '          THEN m2.measurement_id'
    '        WHEN domain_concept_id_2 = {observation_domain_concept_id}'
    '          THEN o2.observation_id'
    '    END AS fact_id_2,'
    '    fr.relationship_concept_id AS relationship_concept_id'
    '  FROM {rdr_dataset_id}.fact_relationship fr'
    '    LEFT JOIN {combined_dataset_id}.{mapping_measurement} m1'
    '      ON m1.src_measurement_id = fr.fact_id_1 AND fr.domain_concept_id_1={'
    'measurement_domain_concept_id}'
    '    LEFT JOIN {combined_dataset_id}.{mapping_observation} o1'
    '      ON o1.src_observation_id = fr.fact_id_1 AND fr.domain_concept_id_1={'
    'observation_domain_concept_id}'
    '    LEFT JOIN {combined_dataset_id}.{mapping_measurement} m2'
    '      ON m2.src_measurement_id = fr.fact_id_2 AND fr.domain_concept_id_2={measurement_domain_concept_id}'
    '    LEFT JOIN {combined_dataset_id}.{mapping_observation} o2'
    '      ON o2.src_observation_id = fr.fact_id_2 AND fr.domain_concept_id_2={observation_domain_concept_id}'
    '    '
    ' UNION ALL '
    '    '
    ' SELECT * from {ehr_dataset}.fact_relationship')
